啥也不是

diff --git a/lab7/2021NKUCS-Compilers-Lab-lab7/Makefile b/lab7/2021NKUCS-Compilers-Lab-lab7/Makefile
--- a/lab7/2021NKUCS-Compilers-Lab-lab7/Makefile
+++ b/lab7/2021NKUCS-Compilers-Lab-lab7/Makefile
@@ -21,14 +21,16 @@ PARSERH ?= $(INC_PATH)/$(addsuffix .h, $(notdir $(basename $(PARSER))))
 TESTCASE = $(shell find $(TEST_PATH) -name "*.sy")
 TESTCASE_NUM = $(words $(TESTCASE))
 LLVM_IR = $(addsuffix _std.ll, $(basename $(TESTCASE)))
+GCC_ASM = $(addsuffix _std.s, $(basename $(TESTCASE)))
 OUTPUT_LAB4 = $(addsuffix .toks, $(basename $(TESTCASE)))
 OUTPUT_LAB5 = $(addsuffix .ast, $(basename $(TESTCASE)))
 OUTPUT_LAB6 = $(addsuffix .ll, $(basename $(TESTCASE)))
+OUTPUT_LAB7 = $(addsuffix .s, $(basename $(TESTCASE)))
 OUTPUT_RES = $(addsuffix .res, $(basename $(TESTCASE)))
 OUTPUT_BIN = $(addsuffix .bin, $(basename $(TESTCASE)))
 OUTPUT_LOG = $(addsuffix .log, $(basename $(TESTCASE)))
 
-.phony:all app run gdb testlab4 testlab5 testlab6 test clean clean-all clean-test clean-app llvmir
+.phony:all app run gdb testlab4 testlab5 testlab6 testlab7 test clean clean-all clean-test clean-app llvmir gccasm
 
 all:app
 
@@ -48,7 +50,7 @@ $(BINARY):$(OBJ)
 app:$(LEXER) $(PARSER) $(BINARY)
 
 run:app
-	@$(BINARY) -o example.ll -i example.sy
+	@$(BINARY) -o example.s -S example.sy
 
 gdb:app
 	@gdb $(BINARY)
@@ -64,13 +66,21 @@ $(TEST_PATH)/%.ast:$(TEST_PATH)/%.sy
 	@$(BINARY) $< -o $@ -a
 
 $(TEST_PATH)/%.ll:$(TEST_PATH)/%.sy
-	@timeout 5s $(BINARY) $< -o $@ -i 2>$(addsuffix .log, $(basename $@))
-	@[ $$? != 0 ] && echo "\033[1;31mFAIL:\033[0m $(notdir $<)" || echo "\033[1;32mSUCCESS:\033[0m $(notdir $<)"
+	@$(BINARY) $< -o $@ -i	
 
 $(TEST_PATH)/%_std.ll:$(TEST_PATH)/%.sy
 	@clang -x c $< -S -m32 -emit-llvm -o $@ 
 
+$(TEST_PATH)/%_std.s:$(TEST_PATH)/%.sy
+	@arm-linux-gnueabihf-gcc -x c $< -S -o $@ 
+
+$(TEST_PATH)/%.s:$(TEST_PATH)/%.sy
+	@timeout 5s $(BINARY) $< -o $@ -S 2>$(addsuffix .log, $(basename $@))
+	@[ $$? != 0 ] && echo "\033[1;31mCOMPILE FAIL:\033[0m $(notdir $<)" || echo "\033[1;32mCOMPILE SUCCESS:\033[0m $(notdir $<)"
+
 llvmir:$(LLVM_IR)
+
+gccasm:$(GCC_ASM)
 
 testlab4:app $(OUTPUT_LAB4)
 
@@ -78,12 +88,14 @@ testlab5:app $(OUTPUT_LAB5)
 
 testlab6:app $(OUTPUT_LAB6)
 
+testlab7:app $(OUTPUT_LAB7)
+
 .ONESHELL:
 test:app
 	@success=0
 	@for file in $(sort $(TESTCASE))
 	do
-		IR=$${file%.*}.ll
+		ASM=$${file%.*}.s
 		LOG=$${file%.*}.log
 		BIN=$${file%.*}.bin
 		RES=$${file%.*}.res
@@ -91,7 +103,7 @@ test:app
 		OUT=$${file%.*}.out
 		FILE=$${file##*/}
 		FILE=$${FILE%.*}
-		timeout 5s $(BINARY) $${file} -o $${IR} -i 2>$${LOG}
+		timeout 5s $(BINARY) $${file} -o $${ASM} -S 2>$${LOG}
 		RETURN_VALUE=$$?
 		if [ $$RETURN_VALUE = 124 ]; then
 			echo "\033[1;31mFAIL:\033[0m $${FILE}\t\033[1;31mCompile Timeout\033[0m"
@@ -101,14 +113,14 @@ test:app
 			continue
 			fi
 		fi
-		clang -o $${BIN} $${IR} $(SYSLIB_PATH)/sylib.c >>$${LOG} 2>&1
+		arm-linux-gnueabihf-gcc -mcpu=cortex-a72 -o $${BIN} $${ASM} $(SYSLIB_PATH)/libsysy.a >>$${LOG} 2>&1
 		if [ $$? != 0 ]; then
 			echo "\033[1;31mFAIL:\033[0m $${FILE}\t\033[1;31mAssemble Error\033[0m"
 		else
 			if [ -f "$${IN}" ]; then
-				timeout 2s $${BIN} <$${IN} >$${RES} 2>>$${LOG}
+				timeout 2s qemu-arm -L /usr/arm-linux-gnueabihf $${BIN} <$${IN} >$${RES} 2>>$${LOG}
 			else
-				timeout 2s $${BIN} >$${RES} 2>>$${LOG}
+				timeout 2s qemu-arm -L /usr/arm-linux-gnueabihf $${BIN} >$${RES} 2>>$${LOG}
 			fi
 			RETURN_VALUE=$$?
 			FINAL=`tail -c 1 $${RES}`
@@ -137,12 +149,8 @@ clean-app:
 	@rm -rf $(BUILD_PATH) $(PARSER) $(LEXER) $(PARSERH)
 
 clean-test:
-	@rm -rf $(OUTPUT_LAB4) $(OUTPUT_LAB5) $(OUTPUT_LAB6) $(OUTPUT_LOG) $(OUTPUT_BIN) $(OUTPUT_RES) $(LLVM_IR) ./example.ast ./example.ll ./example.s
+	@rm -rf $(OUTPUT_LAB4) $(OUTPUT_LAB5) $(OUTPUT_LAB6) $(OUTPUT_LAB7) $(OUTPUT_LOG) $(OUTPUT_BIN) $(OUTPUT_RES) $(LLVM_IR) $(GCC_ASM) ./example.ast ./example.ll ./example.s
 
 clean-all:clean-test clean-app
 
 clean:clean-all
-
-
-byclang:
-	@clang -S -emit-llvm example.cpp -o madebyclang.ll
